const currencyCountryMap = {
  AED: { countryCode: "AE", country: "United Arab Emirates", currencyName: "UAE Dirham" },
  AFN: { countryCode: "AF", country: "Afghanistan", currencyName: "Afghan Afghani" },
  ALL: { countryCode: "AL", country: "Albania", currencyName: "Albanian Lek" },
  AMD: { countryCode: "AM", country: "Armenia", currencyName: "Armenian Dram" },
  ANG: { countryCode: "CW", country: "Curaçao / Sint Maarten", currencyName: "Netherlands Antillean Guilder" },
  AOA: { countryCode: "AO", country: "Angola", currencyName: "Angolan Kwanza" },
  ARS: { countryCode: "AR", country: "Argentina", currencyName: "Argentine Peso" },
  AUD: { countryCode: "AU", country: "Australia", currencyName: "Australian Dollar" },
  AWG: { countryCode: "AW", country: "Aruba", currencyName: "Aruban Florin" },
  AZN: { countryCode: "AZ", country: "Azerbaijan", currencyName: "Azerbaijani Manat" },
  BAM: { countryCode: "BA", country: "Bosnia and Herzegovina", currencyName: "Bosnia-Herzegovina Convertible Mark" },
  BBD: { countryCode: "BB", country: "Barbados", currencyName: "Barbadian Dollar" },
  BDT: { countryCode: "BD", country: "Bangladesh", currencyName: "Bangladeshi Taka" },
  BGN: { countryCode: "BG", country: "Bulgaria", currencyName: "Bulgarian Lev" },
  BHD: { countryCode: "BH", country: "Bahrain", currencyName: "Bahraini Dinar" },
  BIF: { countryCode: "BI", country: "Burundi", currencyName: "Burundian Franc" },
  BMD: { countryCode: "BM", country: "Bermuda", currencyName: "Bermudian Dollar" },
  BND: { countryCode: "BN", country: "Brunei", currencyName: "Brunei Dollar" },
  BOB: { countryCode: "BO", country: "Bolivia", currencyName: "Bolivian Boliviano" },
  BRL: { countryCode: "BR", country: "Brazil", currencyName: "Brazilian Real" },
  BSD: { countryCode: "BS", country: "Bahamas", currencyName: "Bahamian Dollar" },
  BTN: { countryCode: "BT", country: "Bhutan", currencyName: "Bhutanese Ngultrum" },
  BWP: { countryCode: "BW", country: "Botswana", currencyName: "Botswanan Pula" },
  BYN: { countryCode: "BY", country: "Belarus", currencyName: "Belarusian Ruble" },
  BZD: { countryCode: "BZ", country: "Belize", currencyName: "Belizean Dollar" },
  CAD: { countryCode: "CA", country: "Canada", currencyName: "Canadian Dollar" },
  CDF: { countryCode: "CD", country: "Democratic Republic of the Congo", currencyName: "Congolese Franc" },
  CHF: { countryCode: "CH", country: "Switzerland", currencyName: "Swiss Franc" },
  CLF: { countryCode: "CL", country: "Chile", currencyName: "Chilean Unit of Account (UF)" },
  CLP: { countryCode: "CL", country: "Chile", currencyName: "Chilean Peso" },
  CNY: { countryCode: "CN", country: "China", currencyName: "Chinese Yuan" },
  COP: { countryCode: "CO", country: "Colombia", currencyName: "Colombian Peso" },
  CRC: { countryCode: "CR", country: "Costa Rica", currencyName: "Costa Rican Colón" },
  CUP: { countryCode: "CU", country: "Cuba", currencyName: "Cuban Peso" },
  CVE: { countryCode: "CV", country: "Cape Verde", currencyName: "Cape Verdean Escudo" },
  CZK: { countryCode: "CZ", country: "Czech Republic", currencyName: "Czech Koruna" },
  DJF: { countryCode: "DJ", country: "Djibouti", currencyName: "Djiboutian Franc" },
  DKK: { countryCode: "DK", country: "Denmark", currencyName: "Danish Krone" },
  DOP: { countryCode: "DO", country: "Dominican Republic", currencyName: "Dominican Peso" },
  DZD: { countryCode: "DZ", country: "Algeria", currencyName: "Algerian Dinar" },
  EGP: { countryCode: "EG", country: "Egypt", currencyName: "Egyptian Pound" },
  ERN: { countryCode: "ER", country: "Eritrea", currencyName: "Eritrean Nakfa" },
  ETB: { countryCode: "ET", country: "Ethiopia", currencyName: "Ethiopian Birr" },
  EUR: { countryCode: "EU", country: "Eurozone", currencyName: "Euro" },
  FJD: { countryCode: "FJ", country: "Fiji", currencyName: "Fijian Dollar" },
  FKP: { countryCode: "FK", country: "Falkland Islands", currencyName: "Falkland Islands Pound" },
  GBP: { countryCode: "GB", country: "United Kingdom", currencyName: "British Pound" },
  GEL: { countryCode: "GE", country: "Georgia", currencyName: "Georgian Lari" },
  GHS: { countryCode: "GH", country: "Ghana", currencyName: "Ghanaian Cedi" },
  GIP: { countryCode: "GI", country: "Gibraltar", currencyName: "Gibraltar Pound" },
  GMD: { countryCode: "GM", country: "Gambia", currencyName: "Gambian Dalasi" },
  GNF: { countryCode: "GN", country: "Guinea", currencyName: "Guinean Franc" },
  GTQ: { countryCode: "GT", country: "Guatemala", currencyName: "Guatemalan Quetzal" },
  GYD: { countryCode: "GY", country: "Guyana", currencyName: "Guyanaese Dollar" },
  HKD: { countryCode: "HK", country: "Hong Kong", currencyName: "Hong Kong Dollar" },
  HNL: { countryCode: "HN", country: "Honduras", currencyName: "Honduran Lempira" },
  HRK: { countryCode: "HR", country: "Croatia", currencyName: "Croatian Kuna" },
  HTG: { countryCode: "HT", country: "Haiti", currencyName: "Haitian Gourde" },
  HUF: { countryCode: "HU", country: "Hungary", currencyName: "Hungarian Forint" },
  IDR: { countryCode: "ID", country: "Indonesia", currencyName: "Indonesian Rupiah" },
  ILS: { countryCode: "IL", country: "Israel", currencyName: "Israeli New Shekel" },
  INR: { countryCode: "IN", country: "India", currencyName: "Indian Rupee" },
  IQD: { countryCode: "IQ", country: "Iraq", currencyName: "Iraqi Dinar" },
  IRR: { countryCode: "IR", country: "Iran", currencyName: "Iranian Rial" },
  ISK: { countryCode: "IS", country: "Iceland", currencyName: "Icelandic Króna" },
  JMD: { countryCode: "JM", country: "Jamaica", currencyName: "Jamaican Dollar" },
  JOD: { countryCode: "JO", country: "Jordan", currencyName: "Jordanian Dinar" },
  JPY: { countryCode: "JP", country: "Japan", currencyName: "Japanese Yen" },
  KES: { countryCode: "KE", country: "Kenya", currencyName: "Kenyan Shilling" },
  KGS: { countryCode: "KG", country: "Kyrgyzstan", currencyName: "Kyrgystani Som" },
  KHR: { countryCode: "KH", country: "Cambodia", currencyName: "Cambodian Riel" },
  KMF: { countryCode: "KM", country: "Comoros", currencyName: "Comorian Franc" },
  KPW: { countryCode: "KP", country: "North Korea", currencyName: "North Korean Won" },
  KRW: { countryCode: "KR", country: "South Korea", currencyName: "South Korean Won" },
  KWD: { countryCode: "KW", country: "Kuwait", currencyName: "Kuwaiti Dinar" },
  KYD: { countryCode: "KY", country: "Cayman Islands", currencyName: "Cayman Islands Dollar" },
  KZT: { countryCode: "KZ", country: "Kazakhstan", currencyName: "Kazakhstani Tenge" },
  LAK: { countryCode: "LA", country: "Laos", currencyName: "Laotian Kip" },
  LBP: { countryCode: "LB", country: "Lebanon", currencyName: "Lebanese Pound" },
  LKR: { countryCode: "LK", country: "Sri Lanka", currencyName: "Sri Lankan Rupee" },
  LRD: { countryCode: "LR", country: "Liberia", currencyName: "Liberian Dollar" },
  LSL: { countryCode: "LS", country: "Lesotho", currencyName: "Lesotho Loti" },
  LYD: { countryCode: "LY", country: "Libya", currencyName: "Libyan Dinar" },
  MAD: { countryCode: "MA", country: "Morocco", currencyName: "Moroccan Dirham" },
  MDL: { countryCode: "MD", country: "Moldova", currencyName: "Moldovan Leu" },
  MGA: { countryCode: "MG", country: "Madagascar", currencyName: "Malagasy Ariary" },
  MKD: { countryCode: "MK", country: "North Macedonia", currencyName: "Macedonian Denar" },
  MMK: { countryCode: "MM", country: "Myanmar", currencyName: "Myanma Kyat" },
  MNT: { countryCode: "MN", country: "Mongolia", currencyName: "Mongolian Tugrik" },
  MOP: { countryCode: "MO", country: "Macau", currencyName: "Macanese Pataca" },
  MRU: { countryCode: "MR", country: "Mauritania", currencyName: "Mauritanian Ouguiya" },
  MUR: { countryCode: "MU", country: "Mauritius", currencyName: "Mauritian Rupee" },
  MVR: { countryCode: "MV", country: "Maldives", currencyName: "Maldivian Rufiyaa" },
  MWK: { countryCode: "MW", country: "Malawi", currencyName: "Malawian Kwacha" },
  MXN: { countryCode: "MX", country: "Mexico", currencyName: "Mexican Peso" },
  MYR: { countryCode: "MY", country: "Malaysia", currencyName: "Malaysian Ringgit" },
  MZN: { countryCode: "MZ", country: "Mozambique", currencyName: "Mozambican Metical" },
  NAD: { countryCode: "NA", country: "Namibia", currencyName: "Namibian Dollar" },
  NGN: { countryCode: "NG", country: "Nigeria", currencyName: "Nigerian Naira" },
  NIO: { countryCode: "NI", country: "Nicaragua", currencyName: "Nicaraguan Córdoba" },
  NOK: { countryCode: "NO", country: "Norway", currencyName: "Norwegian Krone" },
  NPR: { countryCode: "NP", country: "Nepal", currencyName: "Nepalese Rupee" },
  NZD: { countryCode: "NZ", country: "New Zealand", currencyName: "New Zealand Dollar" },
  OMR: { countryCode: "OM", country: "Oman", currencyName: "Omani Rial" },
  PAB: { countryCode: "PA", country: "Panama", currencyName: "Panamanian Balboa" },
  PEN: { countryCode: "PE", country: "Peru", currencyName: "Peruvian Sol" },
  PGK: { countryCode: "PG", country: "Papua New Guinea", currencyName: "Papua New Guinean Kina" },
  PHP: { countryCode: "PH", country: "Philippines", currencyName: "Philippine Peso" },
  PKR: { countryCode: "PK", country: "Pakistan", currencyName: "Pakistani Rupee" },
  PLN: { countryCode: "PL", country: "Poland", currencyName: "Polish Zloty" },
  PYG: { countryCode: "PY", country: "Paraguay", currencyName: "Paraguayan Guaraní" },
  QAR: { countryCode: "QA", country: "Qatar", currencyName: "Qatari Riyal" },
  RON: { countryCode: "RO", country: "Romania", currencyName: "Romanian Leu" },
  RSD: { countryCode: "RS", country: "Serbia", currencyName: "Serbian Dinar" },
  RUB: { countryCode: "RU", country: "Russia", currencyName: "Russian Ruble" },
  RWF: { countryCode: "RW", country: "Rwanda", currencyName: "Rwandan Franc" },
  SAR: { countryCode: "SA", country: "Saudi Arabia", currencyName: "Saudi Riyal" },
  SBD: { countryCode: "SB", country: "Solomon Islands", currencyName: "Solomon Islands Dollar" },
  SCR: { countryCode: "SC", country: "Seychelles", currencyName: "Seychellois Rupee" },
  SDG: { countryCode: "SD", country: "Sudan", currencyName: "Sudanese Pound" },
  SEK: { countryCode: "SE", country: "Sweden", currencyName: "Swedish Krona" },
  SGD: { countryCode: "SG", country: "Singapore", currencyName: "Singapore Dollar" },
  SHP: { countryCode: "SH", country: "Saint Helena", currencyName: "Saint Helena Pound" },
  SLL: { countryCode: "SL", country: "Sierra Leone", currencyName: "Sierra Leonean Leone" },
  SOS: { countryCode: "SO", country: "Somalia", currencyName: "Somali Shilling" },
  SRD: { countryCode: "SR", country: "Suriname", currencyName: "Surinamese Dollar" },
  SSP: { countryCode: "SS", country: "South Sudan", currencyName: "South Sudanese Pound" },
  STN: { countryCode: "ST", country: "São Tomé and Príncipe", currencyName: "São Tomé and Príncipe Dobra" },
  SYP: { countryCode: "SY", country: "Syria", currencyName: "Syrian Pound" },
  SZL: { countryCode: "SZ", country: "Eswatini", currencyName: "Swazi Lilangeni" },
  THB: { countryCode: "TH", country: "Thailand", currencyName: "Thai Baht" },
  TJS: { countryCode: "TJ", country: "Tajikistan", currencyName: "Tajikistani Somoni" },
  TMT: { countryCode: "TM", country: "Turkmenistan", currencyName: "Turkmenistan Manat" },
  TND: { countryCode: "TN", country: "Tunisia", currencyName: "Tunisian Dinar" },
  TOP: { countryCode: "TO", country: "Tonga", currencyName: "Tongan Paʻanga" },
  TRY: { countryCode: "TR", country: "Turkey", currencyName: "Turkish Lira" },
  TTD: { countryCode: "TT", country: "Trinidad and Tobago", currencyName: "Trinidad and Tobago Dollar" },
  TWD: { countryCode: "TW", country: "Taiwan", currencyName: "New Taiwan Dollar" },
  TZS: { countryCode: "TZ", country: "Tanzania", currencyName: "Tanzanian Shilling" },
  UAH: { countryCode: "UA", country: "Ukraine", currencyName: "Ukrainian Hryvnia" },
  UGX: { countryCode: "UG", country: "Uganda", currencyName: "Ugandan Shilling" },
  USD: { countryCode: "US", country: "United States", currencyName: "US Dollar" },
  UYU: { countryCode: "UY", country: "Uruguay", currencyName: "Uruguayan Peso" },
  UZS: { countryCode: "UZ", country: "Uzbekistan", currencyName: "Uzbekistani Som" },
  VES: { countryCode: "VE", country: "Venezuela", currencyName: "Venezuelan Bolívar" },
  VND: { countryCode: "VN", country: "Vietnam", currencyName: "Vietnamese Dong" },
  VUV: { countryCode: "VU", country: "Vanuatu", currencyName: "Vanuatu Vatu" },
  WST: { countryCode: "WS", country: "Samoa", currencyName: "Samoan Tala" },
  XAF: { countryCode: "CM", country: "Central African CFA Franc Zone", currencyName: "Central African CFA Franc" },
  XCD: { countryCode: "AG", country: "East Caribbean Dollar Zone", currencyName: "East Caribbean Dollar" },
  XOF: { countryCode: "SN", country: "West African CFA Franc Zone", currencyName: "West African CFA Franc" },
  XPF: { countryCode: "PF", country: "French Pacific Territories", currencyName: "CFP Franc" },
  YER: { countryCode: "YE", country: "Yemen", currencyName: "Yemeni Rial" },
  ZAR: { countryCode: "ZA", country: "South Africa", currencyName: "South African Rand" },
  ZMW: { countryCode: "ZM", country: "Zambia", currencyName: "Zambian Kwacha" },
  ZWL: { countryCode: "ZW", country: "Zimbabwe", currencyName: "Zimbabwean Dollar" }
};